{% set name = "xray-vision" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xray-vision-{{ version }}.tar.gz
  sha256: d7ef6dd6eacf7fe611f49d2d5ffb833e9f322e7d528cc7215b6d7a6e15a3c079

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib
    - numpy
    - pandas
    - pyqt
    - scipy
    - sip
    - six

test:
  imports:
    - PyQt5
    - xray_vision
    - xray_vision.backend
    - xray_vision.backend.mpl
    - xray_vision.mask
    - xray_vision.messenger
    - xray_vision.messenger.mpl
    - xray_vision.mpl_plotting
    - xray_vision.qt_widgets
    - xray_vision.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nikea/xray-vision
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Visualization widgets and plotting helpers targeted at X-Ray Sciences

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - CJ-Wright
    - mrakitin
